#!/bin/sh

# Will be executed as user "root".

# Name this file "daemon.sh" in your plugin-archive. It will be renamed to NAME
# during installation

if [ -x /usr/bin/logger ]
then
    /usr/bin/logger "DAEMON Script from Squeezelite Plugin"
fi

if systemctl is-active squeezelite.service
then
	/usr/bin/logger "Disabling squeezelite.service"
	systemctl stop squeezelite.service
	systemctl disable squeezelite.service
fi
exit 0
