#!/bin/sh

# Will be executed as user "root".

# Cleanup of squeezelite Plugin


if [ -x /usr/bin/logger ]
then
    /usr/bin/logger "loxberry-plugin-$pluginname - UNINSTALL Script from Squeezelite Plugin"
fi

pluginname = $(basename $0 .sh)

# Remove Squeezelite from sudoers (need root permission)
if [! -w /etc/sudoers.d/$pluginname ]
	then
		rm -f /etc/sudoers.d/$pluginname
fi

# Remove squeezelox user
deluser --remove-all-files squeezelox

# Currently service is not re-enabled to avoid confusion
# /usr/bin/logger "loxberry-plugin-$pluginname - Disabling squeezelite.service"
# systemctl enable squeezelite.service

# Currently keep user loxberry in group audio - to not affect others
# gpasswd -d loxberry audio

# Cleanup of Debian packages required?
# 

exit 0
