#!/bin/sh

# Will be executed as user "root".

# Cleanup of squeezelite Plugin


if [ -x /usr/bin/logger ]
then
    /usr/bin/logger "loxberry-plugin-$pluginname - UNINSTALL Script from Squeezelite Plugin"
fi

pluginname = $(basename $0 .sh)

# Add Squeezelite to sudoers (need root permission)
if [! -w /etc/sudoers.d/$pluginname ]
	then
		rm -f /etc/sudoers.d/$pluginname
fi

/usr/bin/logger "loxberry-plugin-$pluginname - Disabling squeezelite.service"
systemctl enable squeezelite.service

# Cleanup of Debian packages required?
# apt-get autoremove squeezelite
# 

exit 0
